<?= $this->tag->stylesheetLink("assets/css/layout-datatables.css");?>
<?= $this->tag->stylesheetLink("assets/css/layout-nestable.css");?>

					<!-- 
						PANEL CLASSES:
							panel-default
							panel-danger
							panel-warning
							panel-info
							panel-success

						INFO: 	panel collapse - stored on user localStorage (handled by app.js _panels() function).
								All pannels should have an unique ID or the panel collapse status will not be stored!
					-->
<div id="content" class="dashboard padding-20">
	<div class="row">
		<div class="col-md-9">
			<!-- Panel Tabs Left -->
			<div id="panel-ui-tan-l4" class="panel panel-default menu-type">
				<?= $tree ?>
			</div>
		</div>
		<div class="col-md-3">
			<div class="panel panel-default">
				<div class="panel-heading panel-heading-transparent">
					<strong>ADD TO MENU</strong>
				</div>

				<div class="panel-body">
					<form class="validate" action="menu/create" method="post" enctype="multipart/form-data" data-success="Sent! Thank you!" data-toastr-position="top-right" id="add-menu">
					<input type="hidden" name="menu-type" value="">
						<fieldset>
							<!-- required [php action request] -->
							<div class="row">
								<div class="form-group">
									<div class="col-md-12 col-sm-12">
										<label>Name</label>
										<input type="text" name="name" value="" class="form-control required">
									</div>
								</div>
							</div>
							<div class="row">
								<div class="form-group">
									<div class="col-md-12 col-sm-12">
										<label>Alias</label>
										<input type="text" name="alias" value="" class="form-control required">
									</div>
								</div>
							</div>
							<div class="row">
								<div class="form-group">
									<div class="col-md-12 col-sm-12">
										<label>Layout List</label>
										<select name="layout" class="form-control pointer required">
										<?= $listLayout ?>
										</select>
									</div>
								</div>
							</div>
						</fieldset>
						<div class="row">
							<div class="col-md-12">
								<button type="submit" class="btn btn-success margin-top-30">Add menu item</button>
							</div>
						</div>
					</form>					
				</div>
			</div>
		</div>
	</div>
</div>

<div id="modal-edit" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" style="top:10%;">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <form id="modal-form-edit" class="validate" action="menu/editmenu" method="post"><input type="hidden" name="id-edit" value="34">
                <div class="modal-header"><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                    <h4 class="modal-title">Edit menu item</h4></div>
                <div class="modal-body">
                    <div class="row">
                        <div class="form-group">
                            <div class="col-md-12 col-sm-12"><label>Name</label><input type="text" name="name-edit" value="" class="form-control required"></div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group">
                            <div class="col-md-12 col-sm-12"><label>Alias</label><input type="text" name="alias-edit" value="" class="form-control required"></div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="row">
                        <div class="col-md-12"><button type="submit" class="btn btn-success" id="edit-button">Edit Menu Type</button></div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<div id="modal-add" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" style="top:10%;">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <form id="modal-form-add" class="validate" action="menu/createmenutype" method="post">
                <div class="modal-header"><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                    <h4 class="modal-title">Add Menu Type</h4></div>
                <div class="modal-body">
                    <div class="row">
                        <div class="form-group">
                            <div class="col-md-12 col-sm-12"><label>Name</label><input type="text" name="name-add" value="" class="form-control required"></div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group">
                            <div class="col-md-12 col-sm-12"><label>Sort</label><input type="text" name="sort-add" value="" class="form-control required"></div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="row">
                        <div class="col-md-12"><button type="submit" class="btn btn-success" id="add-button">Add Menu Type</button></div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<div id="removeMenu" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" style="top:10%;">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-header">
			 Xóa Menu Item
			</div>
			<div class="modal-body">
			Bạn chắc chắn muốn xóa Menu này không ?
			</div>
			<div class="modal-footer">
			<div class="row"><div class="col-md-12"><button type="submit" class="btn btn-success" id="yes" style="padding: 0px 20px 0px 20px;">YES</button><button type="submit" class="btn btn-success" id="no" style="padding: 0px 20px 0px 20px;" data-dismiss="modal">NO</button></div></div>

			</div>
			
		</div>
	</div>
</div>

<script type="text/javascript">
	
	toastr.options.timeOut = 2000;
	$(window).on('mousemove', function(e){
		var target = $(e.target);
		// condition 1 : Kiểm tra có phải do move tạo ra ?
		// condition 2 : Đối tượng có phải là tab không ?
		// condition 3 : Đối tượng có đang active không ?
		if($('.dd-dragel').length > 0 && target.data('toggle') == 'tab' && !target.parent().hasClass('active')){
			// Show Tab
			target.tab('show');
		}
	});
	$('.dd').nestable({
		group: 1
	}).on('change',moveElement);
	$('.glyphicon-trash').on('click' , removeMenu);
	$('.glyphicon-edit').on('click' , showModalMenuEdit);
	$('.glyphicon-plus').on('click' , createMenuType);
	// Add Menu Item
	$('#add-menu').on('submit',function(e){
		e.preventDefault();
		$form = $(this);
		$menuTypeId = $('.menu-type .nav-tabs li.active').data('id');
		$name = $form.find('input[name=name]');
		$alias = $form.find('input[name=alias]');
		$layout = $form.find('select[name=layout]');
		$.ajax({
			url: '/admin/menu/createmenu',
			method: 'post',
			data: {name:$name.val(),alias:$alias.val(),menuTypeId:$menuTypeId,layoutId:$layout.val()},
			
			success: function(data){
					if(data.status == true)
					{
						if($('#ttab' + $menuTypeId + ' > .dd').find('.dd-empty').length > 0){
							$('#ttab' + $menuTypeId + ' > .dd').html('<ol class="dd-list"></ol>');
						}
						var menu = $('#ttab' + $menuTypeId + ' > .dd > .dd-list').append('<li class="dd-item" data-id="'+data.id+'" data-alias="'+$alias.val()+'"><span class="glyphicon glyphicon-trash pull-right" aria-hidden="true" style="cursor:pointer;margin-top:10px;margin-right:10px;"></span><span class="glyphicon glyphicon-edit pull-right" aria-hidden="true" style="cursor:pointer;margin-top:10px;margin-right:10px;"></span><div class="dd-handle">'+$name.val()+'</div></li>').find('li[data-id=' + data.id + ']');
						
						menu.find('span.glyphicon-trash').on('click', removeMenu);
						menu.find('span.glyphicon-edit').on('click', showModalMenuEdit);
						$form[0].reset();
						$name.focus();
						toastr.success("Your item menu is added!");
					}
					else
					{
						toastr.error("Your item menu can't added!");
					}
					
				}
		});
	});
	// Function remove Menu
	function removeMenu(e)
	{
		$removeMenu = $('#removeMenu');
		$removeMenu.modal('show');
		$this = $(this).parent();
		$removeMenu.find('#yes').on('click',function(e){
			$.ajax({
				url:'/menu/deletemenu',
				method:'post',
				data: {id:$(this).parent().data('id')},
				success:function(data){
					if(data.status==true)
					{
						var parent = $this.parents('.dd');
						$this.remove();
						if(parent.find('li').length == 0){
							parent.html('<div class="dd-empty"></div>');
						}			
						toastr.success("Your item menu is deleted!");
					}
					else
					{
						toastr.error("Your item menu can't deleted!");
						
					}
					
				}
			});		
		});	
	}
	// Function Show Menu Edit
	function showModalMenuEdit(e)
	{
		$el = $(this).parent();
		// Add value into input
		$nameEdit = $('#modal-edit').find('input[name=name-edit]');
		$aliasEdit = $('#modal-edit').find('input[name=alias-edit]');
		$idEdit = $('#modal-edit').find('input[name=id-edit]');
		$nameEdit.val($el.find('.dd-handle').first().text());
		$aliasEdit.val($el.data('alias'));
		$idEdit.val($el.data('id'));
		$('#modal-edit').modal('show');
		// add Event submit for modal
		$('#modal-form-edit').on('submit',function(e){
			e.preventDefault();
			$form = $(this);
			$nameEdit = $form.find('input[name=name-edit]');
			$aliasEdit = $form.find('input[name=alias-edit]');
			$idEdit = $form.find('input[name=id-edit]');
			$.ajax({
				url:'/admin/menu/editmenu',
				method:'post',
				data: {id:$idEdit.val(),name:$nameEdit.val(),alias:$aliasEdit.val()},
				success:function(data){
					if(data.status==true)
					{
						$('li[data-id=' + $idEdit.val() + ']>.dd-handle').text($nameEdit.val());
						$('li[data-id=' + $idEdit.val() + ']').data('alias',$aliasEdit.val());
						$('#modal-form-edit').modal('hide');
						toastr.success("Your item menu is edited!");
					}
					else
					{
						toastr.error("Your item menu can't edited!");
						
					}
				}
			});	
		});
	}
	
	// Function Create Modal : Create menu type
	function createMenuType(e)
	{
		$('#modal').modal('show');
		// Add menu type
		$('#modal-form-add').on('submit',function(e){
			e.preventDefault();
			$form=$(this);
			$name = $form.find('input[name=name-add]');
			$sort = $form.find('input[name=sort-add]');
			$.ajax({
				url:'/admin/menu/createmenutype',
				method: 'post',
				data: {name:$name.val(),sort:$sort.val()},
				success:function(data){
					if(data.status==true)
					{
						$('#modal').modal('hide');
						$('.nav-tabs:first').append('<li class="" data-id="'+data.id+'"><a href="#ttab'+data.id+'" data-toggle="tab" style="padding-left:30px;padding-right:30px;" aria-expanded="true">'+$name.val()+'</a></li>');
						$('.tab-content').append('<div id="ttab'+data.id+'" class="tab-pane"><div class="dd" data-id="1"><div class="dd-empty"></div></div></div>');
						$('.tab-content #ttab'+data.id+' .dd').nestable({
							group: 1
						}).on('change',moveElement);
						toastr.success("Your Menu Type is Added!");
					}
					else
					{
						toastr.error("Your Menu Type can't Added!");
					}
				}
			});
		});
	}
	function moveElement(e,el) {
		if($(el).prev().length > 0){
			// insertAfter
			var des = $(el).prev().data('id');
			var pos = 'insert';
		}else{
			// appendTo
			var des = $(el).parent().parent().data('id');
			var pos = 'append';
			
		}
		if($(el).length>0)
		{
			var a = $(el).parents('.tab-pane').attr('id').replace('ttab','');
			$.ajax({
				url:'/menu/savemenu',
				method:'post',
				data:{pos:pos,des:des,id:$(el).data('id'),menu_type:a},
			});
		}
	}
</script>