<!doctype html>
<html lang="en-US">
	<head>
		<meta charset="utf-8" />
		<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
		<title>Smarty Admin</title>
		<meta name="description" content="" />
		<meta name="Author" content="Dorin Grigoras [www.stepofweb.com]" />

		<!-- mobile settings -->
		<meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0" />

		<!-- WEB FONTS 
		<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800&amp;subset=latin,latin-ext,cyrillic,cyrillic-ext" rel="stylesheet" type="text/css" />-->

		<!-- CORE CSS -->
		
		<!-- THEME CSS -->
		<?= $this->tag->stylesheetLink("assets/plugins/bootstrap/css/bootstrap.min.css");?>
		<?= $this->tag->stylesheetLink("assets/css/essentials.css");?>
		<?= $this->tag->stylesheetLink("assets/css/layout.css");?>
		<?= $this->tag->stylesheetLink("assets/css/color_scheme/green.css");?>
		<?= $this->tag->stylesheetLink('assets/plugins/toastr/toastr.css')?>
		
		<?= $this->tag->javascriptInclude('assets/plugins/jquery/jquery-2.1.4.min.js')?>
		<?= $this->tag->javascriptInclude('assets/plugins/nestable/jquery.nestable.js')?>
		<?= $this->tag->javascriptInclude('assets/plugins/bootstrap/js/bootstrap.min.js')?>
		<?= $this->tag->javascriptInclude('assets/plugins/toastr/toastr.js')?>
		
	</head>
	<!--
		.boxed = boxed version
	-->
	<body>
		<div id="wrapper" class="clearfix">

					<!-- 
						ASIDE 
						Keep it outside of #wrapper (responsive purpose)
					-->
					<aside id="aside">
						<nav id="sideNav"><!-- MAIN MENU -->
							<ul class="nav nav-list">
								<?php $controller = $this->view->getControllerName();?>
								<li<?=($controller=='index'? ' class="active"':'' )?>><!-- dashboard -->
									<?= $this->tag->linkTo("/", '<i class="main-icon fa fa-dashboard"></i> <span>Dashboard</span>'); ?>
								</li>
								<li<?=($controller=='menu'? ' class="active"':'' )?>><!-- dashboard -->
								<?= $this->tag->linkTo("admin/menu/index", '<i class="main-icon fa fa-bars "></i> <span>Menu</span>'); ?>
									<!-- warning - url used by default by ajax (if eneabled) -->
								</li>
								<li<?=($controller=='layout'? ' class="active"':'')?>><!-- dashboard -->
								<?= $this->tag->linkTo("admin/layout/index", '<i class="main-icon fa fa-bars "></i> <span>Layout</span>'); ?>
									<!-- warning - url used by default by ajax (if eneabled) -->
								</li>
							</ul>
						</nav>
					</aside>
					<header id="header">

				<!-- Mobile Button -->
				<button id="mobileMenuBtn"></button>

				<!-- Logo -->
				<span class="logo pull-left">
					<img src="/assets/images/logo_light.png" alt="admin panel" height="35" />
				</span>

				<form method="get" action="page-search.html" class="search pull-left hidden-xs">
					<input type="text" class="form-control" name="k" placeholder="Search for something..." />
				</form>

				<nav>

					<!-- OPTIONS LIST -->
					<ul class="nav pull-right">

						<!-- USER OPTIONS -->
						<li class="dropdown pull-left">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
								<img class="user-avatar" alt="" src="/assets/images/noavatar.jpg" height="34" /> 
								<span class="user-name">
									<span class="hidden-xs">
										John Doe <i class="fa fa-angle-down"></i>
									</span>
								</span>
							</a>
							<ul class="dropdown-menu hold-on-click">
								<li><!-- my calendar -->
									<a href="calendar.html"><i class="fa fa-calendar"></i> Calendar</a>
								</li>
								<li><!-- my inbox -->
									<a href="#"><i class="fa fa-envelope"></i> Inbox
										<span class="pull-right label label-default">0</span>
									</a>
								</li>
								<li><!-- settings -->
									<a href="page-user-profile.html"><i class="fa fa-cogs"></i> Settings</a>
								</li>

								<li class="divider"></li>

								<li><!-- lockscreen -->
									<a href="page-lock.html"><i class="fa fa-lock"></i> Lock Screen</a>
								</li>
								<li><!-- logout -->
									<a href="page-login.html"><i class="fa fa-power-off"></i> Log Out</a>
								</li>
							</ul>
						</li>
						<!-- /USER OPTIONS -->

					</ul>
					<!-- /OPTIONS LIST -->

				</nav>

			</header>
			<section id="middle">
				<?php echo $this->getContent(); ?>
			</section>
		</div>
	
	</body>
</html>
